site_url: https://liulixian1.dpdns.org/hugo-blog
display_url: https://liulixian1.dpdns.org/hugo-blog

backend:
  name: github
  repo: mengxingdemeng/hugo-blog
  branch: main
  base_url: https://auth.sveltiacms.app
  auth:
    client_id: Ov23li0obatAEyxpFd0o

media_folder: "static/uploads"
public_folder: "/hugo-blog/uploads"

collections:
  - name: posts
    label: 博客文章
    label_singular: 文章
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: md
    format: yaml-frontmatter
    fields:
      - {label: "文章标题", name: title, widget: string}
      - label: "发布时间"
        name: date
        widget: datetime
        format: "yyyy-MM-dd'T'HH:mm:ssXXX"
        date_format: "yyyy/MM/dd"
        time_format: "HH:mm"
      - {label: "是否草稿", name: draft, widget: boolean, default: false}
      - {label: "文章简介", name: description, widget: text, required: false}
      - {label: "分类", name: categories, widget: list, required: false}
      - {label: "标签", name: tags, widget: list, required: false}
      - label: "封面图"
        name: featuredImage
        widget: image
        media_folder: "static/uploads"
        public_folder: "/hugo-blog/uploads"
        required: false
      - {label: "正文内容", name: body, widget: markdown}