name: 每日自动抓取Vjudge刷题数据
on:
  schedule:
    # UTC16:10 = 北京时间00:10 每日执行
    - cron: '10 16 * * *'
  workflow_dispatch:

jobs:
  crawl-task:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: gitee/actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 配置Git提交身份
        run: |
          git config --global user.name "自动机器人"
          git config --global user.email "robot@gitee.com"

      - name: 安装Python requests
        run: pip install requests -i https://pypi.tuna.tsinghua.edu.cn/simple

      # 匹配你scripts文件夹下的爬虫文件
      - name: 运行爬虫抓取数据
        run: python scripts/crawl_vjudge.py

      - name: 提交并推送更新
        env:
          TOKEN: ${{ variables.GIT_TOKEN }}
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "auto: 更新Vjudge刷题数据 $(date +%Y-%m-%d)"
          git remote set-url origin https://${TOKEN}@gitee.com/梦醒的梦/hugo-blog.git
          git push origin main